version: "3.8"
services:
    db:
      image: postgres:13.3
      restart: always
      container_name: gkhn
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: test_db

      volumes:
       - data:/var/lib/postgresql/data

      ports:
        - "5432:5432"

volumes:
  data:

