version: "3.8"
services:
  rabbitmq: 
    image: rabbitmq:3.12.8-management
    container_name: rabbitmq
    hostname: rmq
    ports:
      - "8080:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root

        